### ISSUE TITLE
exif data missing

### ISSUE THREAD

**Issue by quocvu** [aheckmann/gm#358] opened 2015-01-23 02:37 UTC
I am using gm 1.17.0 to orient a jpg. After the operation, the exif info is no longer present in the output file. I believe it should present by default unless I user noProfile()

```
  gm(source)
    .options({imageMagick: true})
    .autoOrient()
    .quality(75)
    .write(target, function (err) {
      if (err) {
        console.log('cannot save', target);
      } else {
        console.log('processed', target);
      }
    });
```

**Comment by lbeschastny** [comment] 2015-06-11 07:59
Looks like a duplicate of #338.

**Comment by rwky** [comment] 2015-06-12 12:45
Yep duplicate of #338

**Closed by rwky** 2015-06-12 12:45 UTC
