### ISSUE TITLE
Getting ECONNRESET error

### ISSUE THREAD

**Issue by vast** [aheckmann/gm#448] opened 2015-09-17 18:03 UTC
OS: Ubuntu 14.04.
Both Imagemagick and GraphicMagick are installed.
gm version: 1.19.0
GraphicMagick version: 1.3.18.

Stacktrace:

```
Error: Error: read ECONNRESET
    at finish (/home/runner/test/node_modules/paper/node_modules/gulp-image-resize/node_modules/gulp-gm/index.js:41:21)
    at gm.<anonymous> (/home/runner/test/node_modules/paper/node_modules/gulp-image-resize/node_modules/async/lib/async.js:485:30)
    at gm.emit (events.js:118:17)
    at gm.<anonymous> (/home/runner/test/node_modules/paper/node_modules/gulp-image-resize/node_modules/gulp-gm/node_modules/gm/lib/getters.js:70:16)
    at Socket.cb (/home/runner/test/node_modules/paper/node_modules/gulp-image-resize/node_modules/gulp-gm/node_modules/gm/lib/command.js:322:16)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
```

Any help or ideas?

**Comment by vast** [comment] 2015-09-17 18:16
Update: downgrading to the previous version (1.18.1) fixes the issue.

**Comment by rwky** [comment] 2015-09-17 18:28
Do you have sample code/images?

**Comment by hughstephens** [comment] 2015-09-18 00:33
Getting the same issue. Almost anything uploaded will fail when trying to .size() on 1.19.0 – 1.18.1 is fine. Will try and put some more info together, but it's pretty consistent...

**Comment by sballesteros** [comment] 2015-09-18 00:44
same here, will try to isolate and report.

**Comment by rwky** [comment] 2015-09-18 08:44
#446 is probably related.

A quick fyi. I've no idea if gm works in node 4.0 (or 4.1) I've not tried it and due to the fast development pace of the 4.x branch I'll wait a bit before trying it.

If someone can put up reproducible code and images by Monday I can take a look next week, all tests are passing so it must be something we don't test for :disappointed:

**Comment by vast** [comment] 2015-09-18 17:04
@rwky, isolated it to large jpg/png. Please have a look at: https://github.com/vast/gm-448

```
⌘ ~/src/gm-448/ (master): ./node_modules/.bin/gulp 
[20:02:39] Using gulpfile ~/src/gm-448/gulpfile.js
[20:02:39] Starting 'default'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Error: write EPIPE
    at finish (/Users/vast/src/gm-448/node_modules/gulp-image-resize/node_modules/gulp-gm/index.js:40:21)
    at gm.<anonymous> (/Users/vast/src/gm-448/node_modules/gulp-image-resize/node_modules/async/lib/async.js:485:30)
    at gm.emit (events.js:118:17)
    at gm.<anonymous> (/Users/vast/src/gm-448/node_modules/gulp-image-resize/node_modules/gulp-gm/node_modules/gm/lib/getters.js:70:16)
    at Socket.cb (/Users/vast/src/gm-448/node_modules/gulp-image-resize/node_modules/gulp-gm/node_modules/gm/lib/command.js:318:16)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at onwriteError (_stream_writable.js:317:10)
    at onwrite (_stream_writable.js:335:5)
    at WritableState.onwrite (_stream_writable.js:105:5)
```

**Comment by rwky** [comment] 2015-09-18 17:13
Excellent, I can reproduce it using that repo, leave it with me.

**Comment by rwky** [comment] 2015-09-19 01:25
This is really weird. I've pinned it down to this line https://github.com/aheckmann/gm/blob/38f5f552ebb7c1c7386839e2388b3e0c4a17b093/index.js#L77

For some reason adding png: before - causes gm to close the pipe early (I'm assuming it's gm and not node being weird).

Unless anyone else can come up with a better solution I'll have to revert that commit which is a shame since it's useful.

**Comment by kapouer** [comment] 2015-09-23 13:30
Same here on debian/sid when generating large (750x19000) jpg with
graphicsmagic 1.3.21
gm 1.19.0
nodejs 4.1.0

**Comment by omahm** [comment] 2015-09-23 13:37
Not just large images, I'm getting this with small jpgs (580 x 320 ~  <100kb) as part of a Gulp task using gulp-image-resize

OSX 10.10.5
graphicsmagic 1.3.21
gm 1.19.0

**Comment by rwky** [comment] 2015-09-23 17:32
Can someone please test the issue-448 branch and confirm that this is resolved? If so I'll merge it in and release a new version to npm.

**Comment by kapouer** [comment] 2015-09-23 17:47
@rwky i can confirm that it works

**Comment by rwky** [comment] 2015-09-23 18:05
OK 1.20.0 is in npm I'll close this.

**Closed by rwky** 2015-09-23 18:05 UTC
Labels: feedback-required

**Comment by adurrive** [comment] 2016-01-27 23:28
It is gm indeed. I've faced this issue randomly, depending on the machine I execute the test on, but in each case I could reproduce it with:
```
cat Periodic_table_large.png | gm identify -
cat Periodic_table_large.png | gm identify png:- (Broken pipe)
```
The result was always unaltered. I'm guessing that knowing the format, gm may not need to parse the whole file to extract the information?
