### ISSUE TITLE
Breaking change in 1.19.0

### ISSUE THREAD

**Issue by garrows** [aheckmann/gm#446] opened 2015-09-17 04:36 UTC
Hi,
Love the module but your latest change seems to have broken things for me.

I'm getting the error for several files.
`improper image header `-' @ error/png.c/ReadPNGImage/3921`

Downgrading to 1.18.1 fixed the problem for me.

**Comment by rwky** [comment] 2015-09-17 10:34
When reporting bugs please include the version of graphicsmagick/imagemagick you're using (gm -version/convert -version) as well as the version of this module and copies of any images you're having problems with.

**Comment by garrows** [comment] 2015-09-18 05:23
Apologies. I'm usually more useful but I was in a rush (and sadly still am)

ImageMagick 6.9.1-10 Q16 x86_64
GraphicsMagick 1.3.21 2015-02-28 Q8

Tried on node v4.0.0 and v0.10.40

I'll try to get you some sample code later on.

**Comment by rwky** [comment] 2015-09-23 18:06
Can you see if this is fixed in 1.20.0?

**Comment by garrows** [comment] 2015-09-23 23:07
That has fixed it for both 0.10 and 4.0. Thank you!

**Closed** 2015-09-23 23:07 UTC
Labels: feedback-required

**Comment by adurrive** [comment] 2016-01-28 12:12
Hello @garrows,

I've looked at most of the problems caused by 1.19.0 and I've made a new pull request. Your issue however would likely fail again.

Currently, the module does not provide the image format of buffers and streams to gm, as you may expect when providing a filename. If you used something like `gm(buffer, 'image.png')`, the second argument is ignored and gm has no idea the buffer is a PNG. In most cases, this is fine since gm is able to find the correct format automatically. But in some others, it simply makes buffers and streams unusable. 

1.19.0 tried to fixed this, but there is no fallback on the automatic mode when the provided format fails. It is still possible to use the automatic format inference however by not providing a filename and using something like `gm(buffer)`. This is essentially the current behavior.

It would be great to look further at the problematic files you used and how you used them to rule out other unforeseen issues. Would you still have them?

**Comment by garrows** [comment] 2016-01-28 12:20
That's unfortunate. If you do have to make the breaking change make sure its on a major version change though. 

The module I was having trouble with is https://github.com/garrows/IMMP which has a few tests which I think were failing with 1.19.0. I hope this helps.

**Comment by adurrive** [comment] 2016-01-28 14:31
Thanks I think I've spotted the issue and it's a miss on my part. I'll fix it and let @rwky decide what to do with the pull request.
